import { FormEvent, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, Check, WalletCards } from "lucide-react";
import { useAuth } from "../context/AuthContext";

export default function Signup(){
 const {signup,confirmSignup,demoMode}=useAuth(); const navigate=useNavigate(); const [name,setName]=useState("");const[email,setEmail]=useState("");const[pw,setPw]=useState("");const[confirm,setConfirm]=useState("");const[code,setCode]=useState("");const[needsCode,setNeedsCode]=useState(false);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError("");if(pw!==confirm){setError("Passwords do not match.");return;}try{setBusy(true);const r=await signup(name,email,pw);if(r.confirmed)navigate("/login");else setNeedsCode(true);}catch(err:any){setError(err.message||"Unable to create account.");}finally{setBusy(false);}}
 async function verify(e:FormEvent){e.preventDefault();try{setBusy(true);await confirmSignup(email,code);navigate("/login");}catch(err:any){setError(err.message||"Invalid verification code.");}finally{setBusy(false);}}
 return <div className="auth-page"><div className="auth-visual"><div className="visual-grid"/><div className="visual-content"><div className="auth-brand"><WalletCards size={22}/> ExpenseFlow</div><h1>Your money,<br/><em>your clarity.</em></h1><p>Track daily expenses, discover patterns and build better financial habits.</p><div className="benefits"><span><Check/> Simple tracking</span><span><Check/> Secure cloud data</span><span><Check/> Useful insights</span></div></div></div><div className="auth-panel"><div className="auth-card"><div className="auth-mobile-logo"><WalletCards/> ExpenseFlow</div><h2>{needsCode?"Verify your email":"Create your account"}</h2><p>{needsCode?"Enter the verification code sent to your email.":"Start your smarter spending journey."}</p>{error&&<div className="form-error">{error}</div>}{needsCode?<form className="auth-form" onSubmit={verify}><label>Verification code<input required value={code} onChange={e=>setCode(e.target.value)} placeholder="123456"/></label><button className="primary-btn" disabled={busy}>{busy?"Verifying…":"Verify account"}<ArrowRight size={18}/></button></form>:<form className="auth-form" onSubmit={submit}><label>Full name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Alex Student"/></label><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input type="password" required value={pw} onChange={e=>setPw(e.target.value)} placeholder="At least 8 characters"/></label><label>Confirm password<input type="password" required value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repeat your password"/></label><button className="primary-btn" disabled={busy}>{busy?"Creating…":"Create account"}<ArrowRight size={18}/></button></form>}<p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p><small className="privacy">Authentication is handled by Amazon Cognito when AWS is configured.</small></div></div></div>
}